services:
  justchat-backend:
    image: ghcr.io/sgobbovista/justchat-backend:latest
    container_name: justchat-backend
    restart: unless-stopped
    ports:
      - "50070:80"
    environment:
      NODE_ENV: production
      PORT: 80
      APP_NAME: JustChat Backend
      ADMIN_USER: admin
      ADMIN_PASSWORD: "admin"
      DATABASE_URL: ""
      DB_SSL: "false"
